[metadata]
name = kami_rst_publisher
version = 3.4
description = kami rst publisher: personalized tool based on docutils and reStructuredText.
long_description = file: README.rst
author = kami lel
classifiers=
   Programming Language :: Python
   Topic :: Text Processing
   Topic :: Text Processing :: Markup
   Topic :: Text Processing :: Markup :: reStructuredText

[options]
include_package_data = True
packages = find:
package_dir =
    =.

install_requires =
   docutils
   myst-docutils>=4.0.0


[options.package_data]
* =
    assets/stylesheets/*.css
    assets/publisher_version_appendix.html
